const tableData = [
  {
    id: 1,
    name: 'Load Balancer 3',
    protocol: 'HTTP',
    port: 3000,
    rule: 'Round robit',
    attachedGroups: 'Kevins VM Groups',
    status: 'Disabled',
  },
  {
    id: 2,
    name: 'Load Balancer 1',
    protocol: 'HTTP',
    port: 443,
    rule: 'Round robit',
    attachedGroups: 'Maureens VM Groups',
    status: 'Starting',
  },
  {
    id: 3,
    name: 'Load Balancer 2',
    protocol: 'HTTP',
    port: 80,
    rule: 'DNS delegation',
    attachedGroups: 'Andrews VM Groups',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Load Balancer 6',
    protocol: 'HTTP',
    port: 3000,
    rule: 'Round robit',
    attachedGroups: 'Marcs VM Groups',
    status: 'Disabled',
  },
  {
    id: 5,
    name: 'Load Balancer 4',
    protocol: 'HTTP',
    port: 443,
    rule: 'Round robit',
    attachedGroups: 'Meis VM Groups',
    status: 'Starting',
  },
  {
    id: 6,
    name: 'Load Balancer 5',
    protocol: 'HTTP',
    port: 80,
    rule: 'DNS delegation',
    attachedGroups: 'Ronjas VM Groups',
    status: 'Active',
  },
];

export default tableData;
